### ISSUE TITLE
Integrate Ratelimiter Headers and Cron Cleanup Timer with Playground UI

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/alloy#66]
## Description

The goal of this issue is to enhance the Playground UI by integrating ratelimiter headers and a cron cleanup timer. These headers and timer values should be displayed on the UI whenever the page is loaded or when a command response is received as part of an API call.

The ratelimiter headers will show the current rate limits (e.g., the number of commands allowed and the remaining commands for the current window). Additionally, the cron cleanup timer will display the remaining time before the next scheduled cleanup of keys in DiceDB.

<img width="918" alt="image" src="https://github.com/user-attachments/assets/bb0ee524-aa95-4ac6-a58e-3fc607ecf4d0">

## Tasks

- Integrate Ratelimit Headers in the UI:
  - Extract x-ratelimit-limit, x-ratelimit-remaining, and x-ratelimit-reset from the API response headers.
  - Display these values in the UI, either in the header or as part of a status bar.
  - Ensure that the values are updated when new commands are executed.

- Display the cron cleanup timer and update it as necessary by getting info from backend (`playground-mono`) .
- Ensure the UI fetches and displays these values on initial page load and on every command response from the server.
- Write unit tests for the UI components.
- Verify the rate limit headers are updated as expected when interacting with the command interface.

> Cron Cleanup Timer: A scheduled task on the backend will run at configurable intervals to clean up expired keys in DiceDB. The UI should show the time remaining before the next cleanup.

> These headers should be extracted from the API responses and displayed in the UI whenever the user executes commands (e.g., /shell/exec/).

> Rate Limiting Headers: The API will return the following headers:
x-ratelimit-limit: Maximum number of requests allowed.
x-ratelimit-remaining: Number of requests remaining in the current window.
x-ratelimit-reset: Timestamp of when the rate limit will reset.

**Comment by lucifercr07** [comment]
@aasifkhan7 assigned, thanks for contributing. Please let me know if any details required regarding this.

**Comment by aasifkhan7** [comment]
https://github.com/DiceDB/playground-web/pull/67
@lucifercr07 I've submitted an initial draft of the PR. I'm still working on figuring out how to fetch the next cleanup time. This is my first contribution to an open-source project, so feedback would be highly appreciated if any improvements are needed. Thanks!

**Comment by lucifercr07** [comment]
@aasifkhan7 would you like to continue work on this, draft PR is raised here: https://github.com/DiceDB/playground-mono/pull/43

**Comment by aasifkhan7** [comment]
Sure, let me take a look at the PR

**Comment by vanshavenger** [comment]
@lucifercr07 also when we execute a command in Playground the first time, the remaining request updates to 998 , it should be 999,
shouldn't the line be addRateLimitHeaders(w, limit, limit-(requestCount), requestCount, currentWindow+int64(window)) this.
as very first request count is 1.

Or is there anything i am missing here, correct me if i am wrong.

**Comment by lucifercr07** [comment]
@aasifkhan7 any updates on this?

**Comment by aasifkhan7** [comment]
@lucifercr07, in the PR https://github.com/DiceDB/playground-mono/pull/43, I noticed that the exposed header is x-last-cleanup-time. However, the UI is intended to display "cleanup time left." How can I retrieve the context for the "next cleanup time"?

**Comment by lucifercr07** [comment]
@aasifkhan7 since we know that cron cleanup frequency happens every 15 mins, we can get next cleanup time by `time.Unix(lastCleanupTime, 0).Add(cronFrequencyInterval) - time.Now())`. Correct?
Let me know if you think we should pass `X-Next-Cleanup-Time` we can also do that change on backend shouldn't be a big one.

**Comment by lucifercr07** [comment]
@vanshavenger yes we can integrate that with our existing `/health` API to avoid values being populated after first call. Let me know if you would like to work on this.
Ref: https://github.com/DiceDB/alloy/issues/66#issuecomment-2427753110

**Comment by aasifkhan7** [comment]
@lucifercr07, I think we should start sending `X-Next-Cleanup-Time` since the UI lacks visibility into the 15-minute interval set in the backend. Currently, only the backend knows about this frequency, but the UI has no context of it. Sending the next cleanup time directly would simplify things. Also, I'd like to take on the corresponding change in mono (it'd be my first contribution to a Golang project). Let me know your thoughts!

**Comment by lucifercr07** [comment]
@aasifkhan7 please go ahead and implement, created an issue for it: https://github.com/DiceDB/playground-mono/issues/47
Please comment on it so that I can assign.

**Comment by lucifercr07** [comment]
Closing merged as part of #76
